use Soujanya
select * from [customer_shopping_behavior ]

--1.what is the total revenue generated by male vs female customers?

select gender, SUM(Purchase_Amount_USD) as revenue
from [customer_shopping_behavior ]
group by Gender

--2. which customers used a discount but still spent more than the average amount?

select customer_id,Purchase_Amount_USD
from [customer_shopping_behavior ]
where Discount_Applied = 'yes' and Purchase_Amount_USD >= (select AVG (Purchase_Amount_USD) from [customer_shopping_behavior ])

--3. which are the top 5 products with the highest average review rating?

select Item_Purchased, ROUND(AVG(Review_Rating::numeric),2) as "Average Product Rating"
from [customer_shopping_behavior ]
group by Item_Purchased
order by AVG(Review_Rating) desc


--4. campare average purchase amounts between standard and express shipping?

select Shipping_Type,
ROUND(AVG(Purchase_Amount_USD),2)
from [customer_shopping_behavior ]
where Shipping_Type in ('Standard','Express')
group by Shipping_Type

--5. Do subscribe customers spend more? compare average spend and total revenue between subcribers and non subcribers

select Subscription_Status,
COUNT(Customer_ID) as total_customers,
ROUND(AVG(Purchase_Amount_USD),2) as avg_spend,
ROUND(SUM(Purchase_Amount_USD),2) as total_revenue
from [customer_shopping_behavior ]
group by Subscription_Status
order by total_revenue, avg_spend desc;

--6. which 5 products have the highest percentage of purchases with discounts appiled?

select Item_Purchased,
ROUND(100 * SUM(case when Discount_Applied = 'yes' then 1 else 0 end )/Count(*),2) as discount_rate
from [customer_shopping_behavior ]
group by Item_Purchased
order by discount_rate desc

--7. segment customers into new, returning, and loyal based on their total number of privous purchases , and show the count of each segment?

with customer_type as (
select Customer_ID, Previous_Purchases,
case
    when Previous_Purchases = 1 then 'New'
	when Previous_Purchases between 2 and 10 then 'Returning'
	else 'loyal'
	end as customer_segment
from [customer_shopping_behavior ]
)

select customer_segment,COUNT(*) as 'number of customers'
from customer_type
group by customer_segment

--8. what are the top 3 most purchesed product within eaxh category?

with item_count as (
select Category,
Item_Purchased,
COUNT(customer_id) as total_orders,
Row_Number() over(partition by category order by count(customer_id)desc) as item_rank
from [customer_shopping_behavior ]
group by Category, Item_Purchased
)

select item_rank, category, item_purchesd, total_orders
from item_counts
where item_rank <= 3


--9. are customers who are repeat buyers (more than 5 previous purchaes) also likely to subscribe?

select Subscription_Status,
COUNT(Customer_ID) as repeat_buyers
from [customer_shopping_behavior ]
where Previous_Purchases > 5
group by Subscription_Status

--10. what is the revenue contribution of each age group?

select Age,
SUM(Purchase_Amount_USD) as total_revenue
from [customer_shopping_behavior ]
group by Age
order by total_revenue desc;